// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaiqevykudxjvyaqdlmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhaXFldnlrdWR4anZ5YXFkbG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTM5NTUsImV4cCI6MjA2MTUyOTk1NX0.1h140rg7T9ka3LjnwXXdhcAG3r0jtP9QqIEedsLLMUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);